name: Setup Ruff
description: 'Configures Ruff for linting and formatting Python code, which does not require a full environment setup.'

inputs:
  requirements-path:
    required: true

runs:
    using: composite
    steps:
        -   name: Get project version with yq
            id: get_python_version
            uses: mikefarah/yq@v4.46.1
            with:
                cmd: yq '.project.requires-python' pyproject.toml

        -   name: Set up Python
            uses: actions/setup-python@v5.6.0
            with:
                python-version: ${{ steps.get_python_version.outputs.result }}

        -   name: Extract Ruff Version
            id: extract_ruff_version
            shell: bash
            run: |
                echo "RUFF_LINE=$(grep "ruff" ${{ inputs.requirements-path }})" >> $GITHUB_OUTPUT

        -   name: Install Ruff
            shell: bash
            run: |
                python -m pip install --upgrade pip
                pip install "${{ steps.extract_ruff_line.outputs.RUFF_LINE }}"