name: Install a Python Package
description: 'Installs a specified Python package from a requirements file, allowing for flexible package management.'

inputs:
    requirements-path:
        required: true
    package:
        required: true

runs:
    using: composite
    steps:
        -   name: Get project version with yq
            id: get_python_version
            uses: mikefarah/yq@v4.46.1
            with:
                cmd: yq '.project.requires-python' pyproject.toml

        -   name: Set up Python
            uses: actions/setup-python@v5.6.0
            with:
                python-version: ${{ steps.get_python_version.outputs.result }}

        -   name: Extract Package Version
            id: extract_package_version
            shell: bash
            run: |
                echo "PACKAGE_LINE=$(grep -w "^${{ inputs.package }}" ${{ inputs.requirements-path }} || echo "${{ inputs.package }}")" >> $GITHUB_OUTPUT

        -   name: Install Package
            shell: bash
            run: |
                python -m pip install --upgrade pip
                pip install "${{ steps.extract_package_version.outputs.PACKAGE_LINE }}"