name: CD

on:
  release:
    types: [published]

jobs:
  publish-to-pypi:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    environment:
      name: testpypi
    permissions:
      id-token: write

    steps:
    - name: Check out Repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Get latest tag
      id: latest_tag
      run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
    - name: Use the tag
      run: echo "The latest tag is ${{ steps.latest_tag.outputs.TAG }}"

    - name: Get project version with yq
      id: get_python_version
      uses: mikefarah/yq@v4.46.1
      with:
        cmd: yq '.project.requires-python' pyproject.toml

    - name: Initialize Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.get_python_version.outputs.result }}

    - name: Install build
      run: >-
        pip install build==1.2.2.post1

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Publish distribution 📦 to PyPI
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION: ${{ github.event.release.tag_name }}
      with:
        packages-dir: dist/
        repository-url: https://pypi.org/legacy/
      uses: pypa/gh-action-pypi-publish@release/v1
